@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.gershaveut.manamod.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;