@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.gershaveut.manamod.network.protocol;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;