@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.gershaveut.manamod;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;