@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.gershaveut.mana_mod.network.protocol;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;