@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.gershaveut.mana_mod;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;