@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.gershaveut.mana_mod.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;